### ISSUE TITLE
How to add markdown-it plugins?

### ISSUE THREAD

**Issue by Julien76** [egoist/vmark#10]
Hi,

I'm using vmark together with vmark-loader.

It works great but I can't find the way to add markdown-it modules to it.
Is that possible?

For example, I want to use ```markdown-it-mermaid```, normally I will use:
```
const md = new MarkdownIt().use(require('markdown-it-mermaid').default)
```
How should I do for vmark?

Thanks

**Comment by egoist** [comment]
I published a new version which adds the `extend` option: https://github.com/egoist/vmark#optionsextend

So you can now use markdown-it plugins like this:

```js
const options = {
  extend(md) {
    md.use(require('markdown-it-plugin'))
  }
}
```
