### ISSUE TITLE
【求助】安装后，运行报错

### ISSUE THREAD

**Issue by dear-lizhihua** [egoist/vmark#7]
示例仓库：https://github.com/dear-lizhihua/vue-cli-demo
报错代码：https://github.com/dear-lizhihua/vue-cli-demo/commit/469b0e1be254747712a304d7a804514e12c92ca2

可能是我不太会使用，不知道哪里出了问题。

**Comment by egoist** [comment]
Maybe related to https://github.com/egoist/vmark-loader/pull/1

Fixed in `vmark-loader@0.1.1`
