### ISSUE TITLE
【求助】解析报错

### ISSUE THREAD

**Issue by dear-lizhihua** [egoist/vmark#8]
示例仓库：https://github.com/dear-lizhihua/vue-cli-demo
报错代码：https://github.com/dear-lizhihua/vue-cli-demo/commit/7dee48865974b37235e304e76bdd3e31dd47ef11
示例来源：https://github.com/wxsms/vue-md-loader/blob/master/example/src/markdown.md

解析正常的 markdown 文件报错
```
./src/test.md
Module parse failed: 'with' in strict mode (86:4)
You may need an appropriate loader to handle this file type.
```

**Comment by egoist** [comment]
Fixed in `vmark@0.1.2`
